export const authConstanst = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
}

export const userConstants = {
  GET_REALTIME_USERS: 'GET_REALTIME_USERS',
  GET_REALTIME_MESSAGES: 'GET_REALTIME_MESSAGES',
}
export const UserConstanst = {
  GET_DATA_USERS: 'GET_DATA_USERS',
  GET_DATA_MESSAGES: 'GET_DATA_MESSAGES',
}
